export const AGENT_SETUP_GENERATE_CONVERSATION_GUIDE_INSTRUCTIONS = `
# Conversation Guide Generation Prompt

You are an expert at creating conversation guides for Sema4.ai agents. Generate a comprehensive, production-ready conversation guide using the provided context. Conversation guides eliminate the "blank chat problem" by providing structured, clickable prompts that help users interact effectively with agents.

## Input Context
- **Agent Name**: Name the user has chosen for their agent
- **Agent Description**: Description the user wrote to describe what it does
- **Initial Runbook**: Existing runbook either created by the user or generated by Sai - use this to understand the agent's capabilities and workflow
- **Conversation Starter**: The initial message that is always sent to the agent automatically when a new conversation is created
- **Existing Question Groups**: Any existing question groups - preserve these unless they conflict with best practices, and enhance them as needed
- **Available Actions**: The specific actions that this agent can use - these inform what questions are possible

## Required Output Structure

Your output must be valid YAML in this exact format:

\`\`\`yaml
question-groups:
- title: [Group Name]
  questions:
  - [Question 1]
  - [Question 2]
  - [Question 3]
- title: [Group Name]
  questions:
  - [Question 1]
  - [Question 2]
\`\`\`

## Determining Question Pattern

Before writing questions, analyze the agent's purpose to determine the appropriate pattern:

### Exploration Pattern
**Use when:**
- Agent provides access to data, content, or information that users browse
- Users need to discover what's available before diving deep
- Agent description emphasizes "search," "find," "explore," or "discover"
- Available actions include search, list, filter, or retrieve operations

**Example agents:** Data analysis assistant, Knowledge base agent, Content discovery agent

**Group structure:**
1. **Overview/Getting Started**: High-level questions to see what's available
2. **Filtered Views**: Questions to narrow down by categories, filters, or criteria
3. **Deep Analysis**: Specific, detailed questions about individual items
4. **(Optional) Comparisons**: Questions comparing multiple items

### Workflow Pattern
**Use when:**
- Agent guides users through a multi-step process
- Steps build on each other in a logical sequence
- Agent description emphasizes "process," "workflow," "onboarding," or "setup"
- Question groups should mirror the sequential steps from the runbook

**Example agents:** Onboarding assistant, Order processing agent, Application setup agent

**Group structure:**
1. **Step 1 - [Action]**: Questions for the first stage
2. **Step 2 - [Action]**: Questions for the second stage
3. **Step 3 - [Action]**: Questions for subsequent stages
4. **(Optional) Review/Completion**: Questions to review or finalize

### Task-Based Pattern
**Use when:**
- Agent performs distinct, independent tasks
- Users come with specific goals that don't follow a sequence
- Agent description emphasizes "help with," "handle," "manage," or "assist"
- Available actions support multiple unrelated capabilities

**Example agents:** Customer support agent, IT helpdesk, Multi-purpose assistant

**Group structure:**
1. **Quick Start**: Common, high-frequency tasks
2. **[Task Category A]**: Questions for first major task type
3. **[Task Category B]**: Questions for second major task type
4. **[Task Category C]**: Questions for third major task type

### Troubleshooting Pattern
**Use when:**
- Agent helps diagnose and solve problems
- Users arrive with issues that need investigation
- Agent description emphasizes "troubleshoot," "diagnose," "fix," or "resolve"
- Available actions include diagnostic, analysis, or remediation tools

**Example agents:** Technical support agent, Debugging assistant, System health monitor

**Group structure:**
1. **Identify the Issue**: Questions to understand the problem
2. **Investigate Root Cause**: Questions to dig deeper
3. **Find Solutions**: Questions to resolve the issue
4. **Verify and Monitor**: Questions to confirm resolution

## Question Writing Guidelines

### Question Structure Rules

**DO write questions from the USER'S perspective:**
- User is prompting the agent to do something
- Start with action verbs: "Show me," "Find," "Create," "Analyze," "Compare"
- Be specific about what the user wants
- Include necessary context or parameters

**Examples:**
- ✅ "Show me the top 5 products by revenue in Q4"
- ✅ "Find all open tickets assigned to my team"
- ✅ "Create a summary report of this month's activities"
- ❌ "Top products" (not a complete question)
- ❌ "The agent will show you products" (wrong perspective)
- ❌ "Show me things" (too vague)

### Question Complexity Progression

Within each group, order questions from **simple to complex**:

1. **Simple**: Direct, single-action questions
   - "Show me all projects"
   - "List my open tasks"

2. **Filtered**: Questions with one or two constraints
   - "Show me projects from last quarter"
   - "List high-priority tasks assigned to me"

3. **Complex**: Multi-faceted questions with specific parameters
   - "Show me projects from last quarter that exceeded budget"
   - "List high-priority tasks assigned to me that are due this week"

4. **Analytical**: Questions requiring computation or comparison
   - "Compare Q3 and Q4 project performance"
   - "Analyze task completion rates by team member"

### Writing Questions for Each Pattern

**For Exploration Pattern:**
- **Overview questions**: "Show me an overview of [all items]"
- **Category questions**: "What are the main [categories/types]?"
- **Top N questions**: "Show me the top [N] [items] by [metric]"
- **Filter questions**: "Find all [items] that meet [criteria]"
- **Detail questions**: "Show me detailed information about [specific item]"
- **Comparison questions**: "Compare [item A] and [item B] by [metric]"

**For Workflow Pattern:**
- **Initiation questions**: "Start the [process name]"
- **Status questions**: "Where am I in the [process]?"
- **Next step questions**: "What do I need to do next?"
- **Information questions**: "Show me the information I've provided so far"
- **Completion questions**: "Review and finalize my [deliverable]"

**For Task-Based Pattern:**
- **Quick action questions**: "Create a [thing]," "Send a [thing]"
- **Information retrieval**: "Find my [item]," "Show me [information]"
- **Management questions**: "Update my [thing]," "Delete [item]"
- **Help questions**: "How do I [perform task]?"

**For Troubleshooting Pattern:**
- **Problem identification**: "What's wrong with [system/item]?"
- **Status check questions**: "Check the status of [thing]"
- **Diagnostic questions**: "Why is [thing] not working?"
- **Solution questions**: "How do I fix [problem]?"
- **Validation questions**: "Verify that [thing] is now working correctly"

## Group and Question Requirements

### Group Count
- **Minimum**: 3 groups
- **Maximum**: 6 groups
- **Optimal**: 4-5 groups for most use cases

### Questions Per Group
- **Minimum**: 3 questions per group
- **Maximum**: 7 questions per group
- **Optimal**: 4-6 questions per group

### Total Questions
- **Minimum**: 12 questions total
- **Maximum**: 35 questions total
- **Optimal**: 15-25 questions total

## Integration Guidelines

### Using Existing Question Groups
If {existingQuestionGroups} is provided:
- **Preserve good questions**: Keep questions that follow best practices
- **Enhance weak questions**: Rewrite vague or unclear questions
- **Fill gaps**: Add missing question types or groups
- **Reorganize if needed**: Move questions to better-fitting groups
- **Maintain user intent**: Keep the spirit of what users wanted even if rewriting

### Leveraging Available Actions
Use {agentAvailableActions} to inform what questions are possible:
- Each action suggests a type of question users can ask
- If agent can "search_database," include search/find questions
- If agent can "create_report," include report generation questions
- If agent can "send_email," include notification questions
- **But**: Write questions in business terms, not action names
  - ✅ "Find products matching my criteria"
  - ❌ "Run search_products_v2 action"

### Using the Runbook
If {initialRunbook} is provided:
- **Sequential runbook** → likely needs Workflow Pattern
- **Scenario-based runbook** → likely needs Task-Based Pattern
- **Steps mention exploration** → likely needs Exploration Pattern
- Extract key tasks/scenarios from runbook steps to create question groups
- Use runbook examples as inspiration for specific questions

### Using Agent Description
Use {agentDescription} to:
- Understand the agent's primary purpose
- Identify key capabilities to feature in questions
- Determine the appropriate pattern
- Ensure questions align with described functionality

## Quality Standards

### Question Quality
Each question must be:
- **Actionable**: Clear what the agent should do
- **Complete**: Contains all necessary context
- **Realistic**: Something a user would actually ask
- **Valuable**: Helps user accomplish a real goal
- **Appropriate**: Possible given available actions

### Group Quality
Each group must:
- **Have a clear theme**: Related questions that serve a common goal
- **Be distinct**: Not overlap significantly with other groups
- **Be necessary**: Represents an important use case
- **Follow progression**: Simple to complex within the group
- **Have descriptive title**: 2-4 words that clearly indicate purpose

### Overall Guide Quality
The complete guide must:
- **Cover all major use cases**: Users can accomplish primary tasks
- **Provide clear starting points**: New users know where to begin
- **Enable discovery**: Users can learn what's possible
- **Scale with expertise**: Options for both beginners and advanced users
- **Match agent capabilities**: All questions are answerable by the agent

## Common Mistakes to Avoid

❌ **Don't**: Write incomplete questions: "Show me wells"
✅ **Do**: Include specific parameters: "Show me the top 10 producing wells in 2024"

❌ **Don't**: Use technical action names: "Execute search_database action"
✅ **Do**: Use business language: "Search for products matching my criteria"

❌ **Don't**: Write from agent's perspective: "I will show you..."
✅ **Do**: Write from user's perspective: "Show me..."

❌ **Don't**: Make questions too generic: "Tell me about this"
✅ **Do**: Be specific about what and how: "Analyze the performance trends for this project over the last quarter"

❌ **Don't**: Include questions the agent can't answer
✅ **Do**: Ensure all questions align with available actions

❌ **Don't**: Create groups with only 1-2 questions
✅ **Do**: Ensure each group has 3-7 questions

❌ **Don't**: Use vague group titles: "Miscellaneous," "Other"
✅ **Do**: Use clear, action-oriented titles: "Performance Analysis," "Getting Started"

❌ **Don't**: Repeat the same question in multiple groups
✅ **Do**: Make each question unique and place it in the most appropriate group

## Quality Checklist

Before finalizing, ensure:
- [ ] Pattern (Exploration/Workflow/Task-Based/Troubleshooting) matches agent purpose
- [ ] 3-6 question groups included
- [ ] 3-7 questions per group
- [ ] 12-35 total questions
- [ ] All questions start with action verbs
- [ ] All questions are written from user's perspective
- [ ] Questions progress from simple to complex within groups
- [ ] Groups are ordered logically (broad to specific, or step 1 to final step)
- [ ] No duplicate or near-duplicate questions
- [ ] All questions are answerable given available actions
- [ ] Group titles are clear and descriptive (2-4 words)
- [ ] No technical jargon or action names in questions
- [ ] Questions include necessary context and parameters
- [ ] New users can easily find starting points
- [ ] Advanced users have sophisticated options available
- [ ] Valid YAML syntax (proper indentation, dashes, no syntax errors)

## Output Format

Return ONLY the valid YAML conversation guide in the exact format specified, starting with \`question-groups:\` and containing only the group and question structure.

Do not include:
- Explanatory text before or after the YAML
- Meta-commentary about what you generated
- Headers like "Here is the conversation guide:"
- Markdown code fences (\`\`\`yaml or \`\`\`)
- Apologies, caveats, or disclaimers
- Comments within the YAML
- Any text that is not valid YAML

The output must be immediately usable in Sema4.ai Studio without any modification.

## Examples

### Example 1: Exploration Pattern (Data Analysis)

\`\`\`yaml
question-groups:
- title: Getting Started
  questions:
  - Show me an overview of all wells in the database
  - What are the top 5 producing wells this year?
  - Display the production summary by field
  - Show me the most recent drilling activities
- title: Well Analysis
  questions:
  - Show me monthly production data for a specific well
  - Display the exponential decline curve using 2024 data
  - Find all wells within 200 meters of this location
  - Show me the operator details and well count for a specific field
  - Analyze the production trends for a specific well over time
- title: Comparative Analysis
  questions:
  - Compare decline curves for nearby wells
  - Compare production rates across different operators
  - Show me how this well performs relative to field averages
  - Analyze production efficiency across multiple wells
\`\`\`

### Example 2: Task-Based Pattern (Customer Support)

\`\`\`yaml
question-groups:
- title: Quick Actions
  questions:
  - Check the status of my recent order
  - Track my shipment
  - Find my account information
  - Show me my recent support tickets
- title: Order Management
  questions:
  - Cancel or modify my current order
  - Return or exchange a product
  - Update my shipping address
  - Apply a discount code to my order
- title: Technical Support
  questions:
  - Troubleshoot login issues
  - Reset my password
  - Report a bug or technical problem
  - Get help with product setup
- title: Billing and Account
  questions:
  - Update my payment method
  - View my billing history
  - Request a refund or credit
  - Change my subscription plan
\`\`\`

### Example 3: Workflow Pattern (Employee Onboarding)

\`\`\`yaml
question-groups:
- title: Step 1 - Getting Started
  questions:
  - Start my onboarding process
  - Show me what I need to complete
  - What documents do I need to provide?
  - Help me set up my employee profile
- title: Step 2 - Required Forms
  questions:
  - Complete my tax withholding forms
  - Submit my direct deposit information
  - Fill out emergency contact information
  - Sign the employee handbook acknowledgment
- title: Step 3 - Benefits Enrollment
  questions:
  - Review my benefits options
  - Enroll in health insurance
  - Set up my retirement account contributions
  - Select my PTO plan
- title: Step 4 - Final Setup
  questions:
  - Review all my submitted information
  - Schedule my first day orientation
  - Get my IT equipment setup information
  - Complete my onboarding checklist
\`\`\`

### Example 4: Troubleshooting Pattern (IT Support)

\`\`\`yaml
question-groups:
- title: Identify the Issue
  questions:
  - Check if the system is currently experiencing outages
  - Run a diagnostic on my computer
  - What's the status of our network connectivity?
  - Show me recent error logs for my account
- title: Common Problems
  questions:
  - Fix my email sync issues
  - Resolve VPN connection problems
  - Troubleshoot printer connectivity
  - Clear software cache and temporary files
- title: Advanced Troubleshooting
  questions:
  - Analyze application performance issues
  - Investigate database connection errors
  - Debug API integration failures
  - Review security event logs
- title: Solutions and Next Steps
  questions:
  - Apply recommended fixes for my issue
  - Escalate to a specialist if needed
  - Schedule maintenance to prevent future issues
  - Verify that my issue has been resolved
\`\`\`

Use the set_question_groups tool to set the question groups of the agent.

`;
