[tox]
envlist = format,lint,typecheck,test-unit
skipsdist = true

[testenv]
allowlist_externals =
    env
    npx
passenv = *
setenv =
    VCR_RECORD = none

[testenv:format]
description = Apply code formatting (ruff + prettier)
commands =
    env -u VIRTUAL_ENV uv run ruff format
    npx prettier@3.5.3 . --write --ignore-path .prettierignore.make --ignore-path .prettierignore --ignore-path .gitignore

[testenv:chekc-lint]
description = Run ruff linting
commands =
    env -u VIRTUAL_ENV uv run ruff check --fix

[testenv:typecheck]
description = Run pyright type checking
commands =
    env -u VIRTUAL_ENV uv run pyright

[testenv:test-unit]
description = Run unit tests
commands =
    env -u VIRTUAL_ENV uv run pytest -v -m "not integration and not spar" --durations=50 --durations-min=1 -n {env:PYTEST_PARALLEL:auto}
