import json
from dataclasses import dataclass, field
from typing import Any, Literal

from agent_platform.core.responses.content.base import ResponseMessageContent
from agent_platform.core.utils import assert_literal_value_valid


@dataclass(frozen=True)
class ResponseToolUseContent(ResponseMessageContent):
    """Represents a tool use request generated by the model.

    This class handles tool usage requests from the model, normalizing input formats
    from different LLM providers (e.g., OpenAI, Claude) into a consistent structure.
    It provides validation and parsing of tool inputs while maintaining
    provider-specific compatibility.

    Raises:
        json.JSONDecodeError: If tool_input_raw is a string and cannot be parsed as
        valid JSON.
        AssertionError: If kind field doesn't match the literal "tool_use".
    """

    tool_call_id: str = field(
        metadata={"description": "Unique identifier for this tool call"},
    )
    """Unique identifier for this tool call"""

    tool_name: str = field(metadata={"description": "Name of the tool being requested"})
    """Name of the tool being requested"""

    tool_input_raw: str = field(
        metadata={
            "description": "Raw tool input as a JSON string.",
        },
    )
    """Raw tool input as a JSON string."""

    _tool_input: dict[str, Any] = field(
        init=False,
        metadata={"description": "Parsed tool input parameters as a dictionary"},
    )
    """Parsed tool input parameters as a dictionary"""

    kind: Literal["tool_use"] = field(
        default="tool_use",
        init=False,
        metadata={"description": "Content kind identifier, always 'tool_use'"},
    )
    """Content kind identifier, always 'tool_use'"""

    def __post_init__(self) -> None:
        """Validates and processes the tool input after initialization.

        Ensures the kind field is valid and converts string inputs to dictionaries.
        """
        assert_literal_value_valid(self, "kind")

        # Handle empty args we probably should handle as empty obj
        if self.tool_input_raw == "":
            object.__setattr__(self, "tool_input_raw", "{}")

        # Try to parse the tool input and remove any odd empty
        # keys (e.g. {"":""}) This is somehow a scenario that can happen
        try:
            tool_input_parsed = json.loads(self.tool_input_raw)
        except json.JSONDecodeError as exc:
            raise ValueError("tool_input_raw is not valid JSON") from exc

        # If for some reason tool_input_raw was null, then we would now
        # have a tool_input_parsed of None. We should handle this gracefully.
        if tool_input_parsed is None:
            tool_input_parsed = {}

        # Remove any empty keys
        new_tool_input_parsed = {}
        for key, value in tool_input_parsed.items():
            if key == "":
                continue
            new_tool_input_parsed[key] = value

        object.__setattr__(self, "tool_input_raw", json.dumps(new_tool_input_parsed))
        object.__setattr__(self, "_tool_input", new_tool_input_parsed)

    @property
    def tool_input(self) -> dict[str, Any]:
        """Returns the tool input as a dictionary.

        This property ensures that the tool input is always a dictionary,
        even if it was originally provided as a string.
        """
        return self._tool_input

    def model_dump(self) -> dict:
        """Returns a dictionary representation suitable for serialization."""
        return {
            **super().model_dump(),
            "tool_call_id": self.tool_call_id,
            "tool_name": self.tool_name,
            "tool_input_raw": self.tool_input_raw,
        }

    @classmethod
    def model_validate(cls, data: dict) -> "ResponseToolUseContent":
        """Create a tool use content from a dictionary."""
        data = data.copy()
        # Remove 'kind' if present since it's not an init parameter
        if "kind" in data:
            data.pop("kind")
        return cls(**data)


ResponseMessageContent.register_content_kind("tool_use", ResponseToolUseContent)
