name: Pre-Release Workflow

on:
  workflow_dispatch: # Manual trigger, adjust as needed
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - pre
          - pre-major
          - pre-minor
          - pre-patch
          - pre-build
          - new-pre-major
          - new-pre-minor
          - new-pre-patch

jobs:
  prerelease:
    if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest

    steps:
      - name: Display initiator
        run: echo "This workflow was triggered by $GITHUB_ACTOR"

      - name: Checkout and Pull latest
        uses: Sema4AI/agent-server-team-gh-workflows/.github/actions/checkout_pull_latest@v0.9.0

      - name: Set up versionbump
        uses: Sema4AI/agent-server-team-gh-workflows/.github/actions/setup_versionbump@v0.9.0
        with:
          go_version: "1.22.2"
          versionbump_version: "v0.7.0"

      - name: Bump version
        run: |
          git config --global user.email "agent-team@no-reply.sema4.ai"
          git config --global user.name "Sema4.ai Agent Team"
          if [[ "${{ github.event.inputs.bump_type }}" != *"pre"* ]]; then
            echo "Invalid bump type. Exiting."
            exit 1
          fi
          versionbump ${{ github.event.inputs.bump_type }} --no-prompt
          echo "Version bumped successfully."
          git push origin HEAD --tags

  build-prerelease:
    uses: ./.github/workflows/sub-main-test-build-release.yml
    with:
      python_version: "3.11"
      node_version: 18
      release_channel: beta
      windows_runner: "windows-winserver-2022-sandbox"
    secrets:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      MACOS_APP_ID_FOR_NOTARIZATION_SEMA4AI: ${{ secrets.MACOS_APP_ID_FOR_NOTARIZATION_SEMA4AI }}
      MACOS_APP_ID_PASSWORD_FOR_NOTARIZATION_SEMA4AI: ${{ secrets.MACOS_APP_ID_PASSWORD_FOR_NOTARIZATION_SEMA4AI }}
      MACOS_TEAM_ID_FOR_NOTARIZATION_SEMA4AI: ${{ secrets.MACOS_TEAM_ID_FOR_NOTARIZATION_SEMA4AI }}
      MACOS_SIGNING_CERT_SEMA4AI: ${{ secrets.MACOS_SIGNING_CERT_SEMA4AI }}
      MACOS_SIGNING_CERT_PASSWORD_SEMA4AI: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD_SEMA4AI }}
      MACOS_SIGNING_CERT_NAME_SEMA4AI: ${{ secrets.MACOS_SIGNING_CERT_NAME_SEMA4AI }}
      WIN_SIGN_AZURE_KEY_VAULT_URL_SEMA4AI: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_URL_SEMA4AI }}
      WIN_SIGN_AZURE_KEY_VAULT_CLIENT_ID_SEMA4AI: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_ID_SEMA4AI }}
      WIN_SIGN_AZURE_KEY_VAULT_TENANT_ID_SEMA4AI: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_TENANT_ID_SEMA4AI }}
      WIN_SIGN_AZURE_KEY_VAULT_CLIENT_SECRET_SEMA4AI: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CLIENT_SECRET_SEMA4AI }}
      WIN_SIGN_AZURE_KEY_VAULT_CERTIFICATE_NAME_SEMA4AI: ${{ secrets.WIN_SIGN_AZURE_KEY_VAULT_CERTIFICATE_NAME_SEMA4AI }}
