name: Publish Agent Server to GitHub Releases

# This job should generally be the last in a series of jobs that test and build.

on:
  workflow_call:
    inputs:
      agent_server_version:
        description: The version of the agent server being released
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  publish-to-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Pull Latest
        uses: Sema4AI/agent-server-team-gh-workflows/.github/actions/checkout_pull_latest@v1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: agent-server-release-packages
          path: dist

      - name: Create GitHub Release
        uses: Sema4AI/agent-server-team-gh-workflows/.github/actions/create_gh_release@v1
        with:
          release_version: ${{ inputs.agent_server_version }}
