name: 'Install NPM Dependencies'
description: 'Setup Node.js and install local npm dependencies'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: true
    default: '18'
  npm_auth_token:
    description: 'Token for npm registry authentication'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Configure NPM
      shell: bash
      working-directory: ./agent-server-interface
      run: |
        cat << EOF > "./.npmrc"
        registry=https://registry.npmjs.org/
        @robocorp:registry=https://npm.pkg.github.com/
        @sema4ai:registry=https://npm.pkg.github.com/
        //npm.pkg.github.com/:_authToken=${{ inputs.npm_auth_token }}
        EOF

    - name: Install NPM dependencies
      shell: bash
      working-directory: ./agent-server-interface
      run: npm install
