import json
from copy import deepcopy
from dataclasses import asdict, dataclass, field
from typing import Any, Literal, TypeVar

from agent_server_types_v2.responses.content.base import ResponseMessageContent


@dataclass(frozen=True)
class TokenUsage:
    """Represents token usage statistics from a model's response.

    This class provides a structured format for tracking token consumption,
    including input, output, and total tokens used in a model interaction.
    """

    input_tokens: int = field(
        default=0,
        metadata={"description": "Number of input tokens processed by the model"},
    )
    """Number of input tokens processed by the model"""

    output_tokens: int = field(
        default=0,
        metadata={"description": "Number of output tokens generated by the model"},
    )
    """Number of output tokens generated by the model"""

    total_tokens: int = field(
        default=0,
        metadata={
            "description": "Total number of tokens (input + output) used in the "
            "interaction",
        },
    )
    """Total number of tokens (input + output) used in the interaction"""


T = TypeVar("T", bound="ResponseMessage")


@dataclass(frozen=True, kw_only=True)
class ResponseMessage:
    """A response message from a language model hosted on a platform.

    This class represents a response message from a language model,
    providing a structured format for both content and metadata. It
    supports multi-modal content (text, images, audio, documents) and
    includes standardized fields for model metrics and usage data.
    """

    content: list[ResponseMessageContent]
    """The contents of the model's response."""

    role: Literal["agent"]
    """The role of the message sender."""

    raw_response: Any | None = field(
        default=None,
        metadata={"description": "The raw response from the model"},
    )
    """The raw response from the model"""

    stop_reason: str | None = field(
        default=None,
        metadata={
            "description": "The reason why the response stopped "
            "(e.g., stop_sequence, max_tokens)",
        },
    )
    """The reason why the response stopped (e.g., stop_sequence, max_tokens)"""

    usage: TokenUsage = field(
        default_factory=TokenUsage,
        metadata={"description": "Token usage statistics for the model interaction"},
    )
    """Token usage statistics for the model interaction"""

    metrics: dict[str, Any] = field(
        default_factory=dict,
        metadata={"description": "Model performance metrics and timing information"},
    )
    """Model performance metrics and timing information"""

    metadata: dict[str, Any] = field(
        default_factory=dict,
        metadata={"description": "Additional metadata about the response generation"},
    )
    """Additional metadata about the response generation"""

    additional_response_fields: dict[str, Any] = field(
        default_factory=dict,
        metadata={
            "description": "Provider-specific response fields not "
            "covered by other attributes",
        },
    )
    """Provider-specific response fields not covered by other attributes"""

    @classmethod
    def model_validate(cls: type[T], obj: dict[str, Any]) -> T:
        """Create a ResponseMessage instance from a dictionary.

        Args:
            obj: A dictionary containing the data to create a ResponseMessage.

        Returns:
            A new ResponseMessage instance.
        """
        # Create a copy to avoid modifying the input
        data = deepcopy(obj)

        # Handle nested TokenUsage if present
        if "usage" in data and isinstance(data["usage"], dict):
            data["usage"] = TokenUsage(**data["usage"])

        # Handle nested content items with proper type discrimination
        if "content" in data and isinstance(data["content"], list):
            validated_content = []

            for content_item in data["content"]:
                # Each content item should have a 'kind' field for type discrimination
                if not isinstance(content_item, dict) or "kind" not in content_item:
                    raise ValueError(
                        "Content item missing 'kind' field for type discrimination",
                    )

                # Use the ResponseMessageContent's model_validate to create the
                # appropriate content type
                validated_item = ResponseMessageContent.model_validate(content_item)
                validated_content.append(validated_item)

            data["content"] = validated_content

        # Create the instance
        return cls(**data)

    @classmethod
    def model_validate_json(cls: type[T], json_data: str) -> T:
        """Create a ResponseMessage instance from a JSON string.

        Args:
            json_data: A JSON string containing the data to create a ResponseMessage.

        Returns:
            A new ResponseMessage instance.
        """
        data = json.loads(json_data)
        return cls.model_validate(data)

    def model_dump(self, exclude_none: bool = False) -> dict[str, Any]:
        """Convert the ResponseMessage to a dictionary.

        Args:
            exclude_none: If True, exclude fields with None values.

        Returns:
            A dictionary representation of the ResponseMessage.
        """
        data = asdict(self)

        if exclude_none:
            # Remove None values
            return {k: v for k, v in data.items() if v is not None}

        return data

    def model_dump_json(
        self,
        exclude_none: bool = False,
        indent: int | None = None,
    ) -> str:
        """Convert the ResponseMessage to a JSON string.

        Args:
            exclude_none: If True, exclude fields with None values.
            indent: Number of spaces for indentation in the JSON output.

        Returns:
            A JSON string representation of the ResponseMessage.
        """
        data = self.model_dump(exclude_none=exclude_none)
        return json.dumps(data, indent=indent)
