from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Annotated, Any, Literal, TypedDict

# --- Type Aliases ---

PlanStatus = Literal["pending", "in_progress", "blocked", "completed", "skipped"]
"""Defines the possible execution statuses for a single plan step."""

FeedbackLevel = Literal["info", "warning", "critical"]
"""Defines the severity levels for notes and feedback messages."""

PlanExecutionPhase = Literal[
    "initial",
    "triage",
    "planning",
    "executing-step",
    "monitoring",
    "finalizing",
    "done",
]
"""Defines the possible execution phases for a plan."""

# --- Data Schemas ---


class NoteEntry(TypedDict):
    """A structured entry for logging notes against a plan step."""

    timestamp: str
    note: str
    level: FeedbackLevel


class MonitorFeedbackEntry(TypedDict):
    """A structured feedback entry generated by the monitor for the controller."""

    timestamp: str
    message: str
    level: FeedbackLevel
    related_steps: Sequence[str]


@dataclass(slots=True)
class PlanStepInput:
    """The external schema for defining a plan step, used in tool calls.

    This class defines the contract for the `define_plan` tool. It contains the
    immutable properties of a plan step as provided by the planning agent.
    """

    step_id: Annotated[str, "Unique, machine-readable identifier for the step (e.g., 'fetch-user-data')."]
    title: Annotated[str, "A brief, human-readable summary of the step's goal (e.g., 'Fetch User Data')."]
    description: Annotated[str, "Clear, operational instructions for the execution agent, derived from the Runbook."]
    success_criteria: Annotated[str, "An objective, evidence-based definition of done for the step."]


@dataclass(slots=True)
class PlanStep:
    """The internal, stateful representation of a step in the execution plan.

    This class holds both the immutable definition of a step (from PlanStepInput)
    and its mutable execution state, such as its status and logged notes.
    """

    # -- Core Definition (Immutable after creation) --
    step_id: str
    title: str
    description: str
    success_criteria: str

    # -- Execution State (Mutable) --
    status: PlanStatus = "pending"
    notes: list[NoteEntry] = field(default_factory=list)
    last_updated: str = field(default_factory=lambda: datetime.now(UTC).isoformat(timespec="seconds"))

    @classmethod
    def from_input(cls, data: PlanStepInput) -> "PlanStep":
        """Factory method to create a `PlanStep` from a `PlanStepInput` object.

        This is the standard way to convert the external plan definition into the
        internal, stateful object used by the executor.
        """
        return cls(
            step_id=data.step_id,
            title=data.title,
            description=data.description,
            success_criteria=data.success_criteria,
        )

    def to_metadata(self) -> dict[str, Any]:
        """Returns a JSON-serializable dictionary representation of the step.

        This method is used to generate payloads for UI consumption, logging,
        and other metadata purposes.
        """
        return {
            "step_id": self.step_id,
            "title": self.title,
            "description": self.description,
            "success_criteria": self.success_criteria,
            "status": self.status,
            "notes": list(self.notes),  # Create a shallow copy
            "last_updated": self.last_updated,
        }
