"""Semantic data model types, utilities, and validation.

This module contains the core types and utilities for working with
semantic data models, which describe collections of database tables
with their relationships and metadata.
"""

from agent_platform.core.semantic_data_model.schemas import (
    DocumentExtraction,
    ExtractionEvent,
    JsonData,
    LineageEvent,
    Schema,
    SchemaData,
    Transformation,
    TransformationEvent,
    Validation,
    ValidationEvent,
    ValidationResult,
    normalize_schema_name,
)
from agent_platform.core.semantic_data_model.service import (
    DocumentService,
    DocumentServiceProtocol,
    ExtractJob,
    SchemaService,
    SchemaServiceProtocol,
)
from agent_platform.core.semantic_data_model.types import (
    # Enums
    CATEGORIES,
    # Type aliases
    QUERY_PARAMETER_TYPE_TO_PYTHON,
    # TypedDicts
    BaseTable,
    CategoriesType,
    CortexSearchService,
    DataConnectionSnapshotMetadata,
    Dimension,
    Fact,
    FileReference,
    FileSnapshotMetadata,
    Filter,
    InputDataConnectionSnapshot,
    LogicalTable,
    Metric,
    PrimaryKey,
    # Pydantic models
    QueryParameter,
    QueryParameterDataType,
    Relationship,
    RelationshipColumn,
    SampleValue,
    SemanticDataModel,
    SemanticDataModelMetadata,
    TimeDimension,
    ValidationMessage,
    ValidationMessageKind,
    ValidationMessageLevel,
    VerifiedQuery,
    # Exceptions
    VerifiedQueryNameError,
    VerifiedQueryNLQError,
    VerifiedQueryParameterError,
    VerifiedQuerySQLError,
    # Dataclasses
    VerifiedQueryValidationContext,
    VerifiedQueryValidationError,
)
from agent_platform.core.semantic_data_model.utils import (
    extract_missing_parameters,
    extract_parameters_from_sql,
)
from agent_platform.core.semantic_data_model.validation import (
    DataConnectionInfo,
    DataFrameConnectionInfo,
    EmptyFileReference,
    FileConnectionInfo,
    References,
    validate_semantic_model_payload_and_extract_references,
)

__all__ = [
    "CATEGORIES",
    "QUERY_PARAMETER_TYPE_TO_PYTHON",
    "BaseTable",
    "CategoriesType",
    "CortexSearchService",
    "DataConnectionInfo",
    "DataConnectionSnapshotMetadata",
    "DataFrameConnectionInfo",
    "Dimension",
    "DocumentExtraction",
    "DocumentService",
    "DocumentServiceProtocol",
    "EmptyFileReference",
    "ExtractJob",
    "ExtractionEvent",
    "Fact",
    "FileConnectionInfo",
    "FileReference",
    "FileSnapshotMetadata",
    "Filter",
    "InputDataConnectionSnapshot",
    "JsonData",
    "LineageEvent",
    "LogicalTable",
    "Metric",
    "PrimaryKey",
    "QueryParameter",
    "QueryParameterDataType",
    "References",
    "Relationship",
    "RelationshipColumn",
    "SampleValue",
    "Schema",
    "SchemaData",
    "SchemaService",
    "SchemaServiceProtocol",
    "SemanticDataModel",
    "SemanticDataModelMetadata",
    "TimeDimension",
    "Transformation",
    "TransformationEvent",
    "Validation",
    "ValidationEvent",
    "ValidationMessage",
    "ValidationMessageKind",
    "ValidationMessageLevel",
    "ValidationResult",
    "VerifiedQuery",
    "VerifiedQueryNLQError",
    "VerifiedQueryNameError",
    "VerifiedQueryParameterError",
    "VerifiedQuerySQLError",
    "VerifiedQueryValidationContext",
    "VerifiedQueryValidationError",
    "extract_missing_parameters",
    "extract_parameters_from_sql",
    "normalize_schema_name",
    "validate_semantic_model_payload_and_extract_references",
]
