DROP FUNCTION IF EXISTS v2.check_user_access;

DROP TABLE IF EXISTS v2.otel_artifact CASCADE;
DROP TABLE IF EXISTS v2.memory CASCADE;
DROP TABLE IF EXISTS v2.file_owner CASCADE;
DROP TABLE IF EXISTS v2.scoped_storage CASCADE;
DROP TABLE IF EXISTS v2.thread_message CASCADE;
DROP TABLE IF EXISTS v2.thread CASCADE;
DROP TABLE IF EXISTS v2.agent_run_steps CASCADE;
DROP TABLE IF EXISTS v2.agent_runs CASCADE;
DROP TABLE IF EXISTS v2.agent CASCADE;
DROP TABLE IF EXISTS v2.user CASCADE;

DROP SCHEMA IF EXISTS v2 CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";