import typing
from typing import Any

from structlog import get_logger

if typing.TYPE_CHECKING:
    from agent_platform.core.data_connections.data_connections import DataConnection
    from agent_platform.core.payloads.data_connection import (
        ColumnInfo,
        DataConnectionsInspectRequest,
        DataConnectionsInspectResponse,
        PostgresDataConnectionConfiguration,
        RedshiftDataConnectionConfiguration,
        SnowflakeDataConnectionConfiguration,
        SQLiteDataConnectionConfiguration,
        TableInfo,
        TableToInspect,
    )

logger = get_logger(__name__)


class DataConnectionInspector:
    """Inspector for extracting metadata from data connections using ibis."""

    def __init__(self, data_connection: "DataConnection", request: "DataConnectionsInspectRequest"):
        self.data_connection = data_connection
        self.request = request

    async def inspect_connection(
        self,
    ) -> "DataConnectionsInspectResponse":
        """
        Inspect a data connection and return table/column metadata.

        Returns:
            DataConnectionsInspectResponse with table and column information
        """
        from agent_platform.core.payloads.data_connection import (
            DataConnectionsInspectResponse,
        )

        # Create ibis connection based on engine type
        connection = await self.create_ibis_connection(self.data_connection)

        # Get all tables if none specified
        if not self.request.tables_to_inspect:
            tables_to_inspect = await self._get_all_tables(connection)
        else:
            tables_to_inspect = self.request.tables_to_inspect

        table_infos = []
        if self.request.inspect_columns:
            for table_spec in tables_to_inspect:
                table_info = await self._inspect_table(connection, table_spec)
                table_infos.append(table_info)

        return DataConnectionsInspectResponse(tables=table_infos)

    @classmethod
    async def create_ibis_connection(cls, data_connection: "DataConnection") -> Any:
        """Create an ibis connection based on the data connection configuration."""
        from agent_platform.core.payloads.data_connection import (
            PostgresDataConnectionConfiguration,
            RedshiftDataConnectionConfiguration,
            SnowflakeDataConnectionConfiguration,
            SQLiteDataConnectionConfiguration,
        )

        engine = data_connection.engine
        config = data_connection.configuration

        if engine == "sqlite":
            return await cls._create_sqlite_connection(
                typing.cast(SQLiteDataConnectionConfiguration, config)
            )
        elif engine == "postgres":
            return await cls._create_postgres_connection(
                typing.cast(PostgresDataConnectionConfiguration, config)
            )
        elif engine == "redshift":
            return await cls._create_redshift_connection(
                typing.cast(RedshiftDataConnectionConfiguration, config)
            )
        elif engine == "snowflake":
            return await cls._create_snowflake_connection(
                typing.cast(SnowflakeDataConnectionConfiguration, config)
            )
        else:
            raise ValueError(f"Unsupported engine for inspection: {engine}")

    @classmethod
    async def _create_sqlite_connection(cls, config: "SQLiteDataConnectionConfiguration") -> Any:
        """Create SQLite ibis connection."""
        import ibis

        return ibis.sqlite.connect(config.db_file)

    @classmethod
    async def _create_postgres_connection(
        cls, config: "PostgresDataConnectionConfiguration"
    ) -> Any:
        """Create PostgreSQL ibis connection."""
        import ibis

        return ibis.postgres.connect(
            host=config.host,
            port=int(config.port),
            database=config.database,
            user=config.user,
            password=config.password,
            schema=config.schema,
        )

    @classmethod
    async def _create_redshift_connection(
        cls, config: "RedshiftDataConnectionConfiguration"
    ) -> Any:
        """Create Redshift ibis connection."""
        import ibis

        return ibis.postgres.connect(
            host=config.host,
            port=int(config.port),
            database=config.database,
            user=config.user,
            password=config.password,
            schema=config.schema,
        )

    @classmethod
    async def _create_snowflake_connection(
        cls, config: "SnowflakeDataConnectionConfiguration"
    ) -> Any:
        """Create Snowflake ibis connection."""
        import ibis

        # Commented out code (generated by the LLM: is this
        # really something that could be supported? --
        # SnowflakeDataConnectionConfiguration typing doesn't
        # really support it)
        # if config.credential_type == "custom-key-pair":
        #     # For custom key pair authentication
        #     return ibis.snowflake.connect(
        #         account=config.account,
        #         user=config.user,
        #         private_key_path=config.private_key_path,
        #         warehouse=config.warehouse,
        #         database=config.database,
        #         schema=config.schema,
        #         role=config.role,
        #         private_key_passphrase=config.private_key_passphrase,
        #     )
        # else:
        # For password-based authentication
        return ibis.snowflake.connect(
            account=config.account,
            user=config.user,
            password=config.password,
            warehouse=config.warehouse,
            database=config.database,
            schema=config.schema,
            role=config.role,
        )

    @classmethod
    async def _get_all_tables(cls, connection: Any) -> "list[TableToInspect]":
        """Get all tables from the connection."""
        from agent_platform.core.payloads.data_connection import TableToInspect

        # Get list of tables from ibis
        tables = connection.list_tables()

        table_specs = []
        for table_name in tables:
            # For most databases, we can get schema info from the connection
            schema = None
            database = None

            if hasattr(connection, "current_schema"):
                schema = connection.current_schema
            if hasattr(connection, "current_database"):
                database = connection.current_database

            table_specs.append(
                TableToInspect(
                    name=table_name,
                    database=database,
                    schema=schema,
                )
            )

        return table_specs

    async def _inspect_table(self, connection: Any, table_spec: "TableToInspect") -> "TableInfo":
        """Inspect a specific table and return its metadata."""
        from agent_platform.core.payloads.data_connection import TableInfo

        # Get the table reference
        table = connection.table(table_spec.name)

        # Get column information
        columns = []
        columns_to_inspect = []
        for column_name in table.schema().names:
            # Skip columns if specific columns are requested and this one isn't in the list
            if (
                table_spec.columns_to_inspect is not None
                and column_name not in table_spec.columns_to_inspect
            ):
                continue
            columns_to_inspect.append(column_name)

        if columns_to_inspect:
            # Execute query to get sample values
            sample_query = table.select(columns_to_inspect).limit(self.request.n_sample_rows)

            sample_table = sample_query.to_pyarrow()
        else:
            sample_table = None

        for column_name in columns_to_inspect:
            column_info = await self._inspect_column(table, column_name, sample_table)
            columns.append(column_info)

        return TableInfo(
            name=table_spec.name,
            database=table_spec.database,
            schema=table_spec.schema,
            description=None,  # TODO: Add description extraction if available
            columns=columns,
        )

    async def _inspect_column(
        self, table: Any, column_name: str, sample_table: Any | None
    ) -> "ColumnInfo":
        """Inspect a specific column and return its metadata."""
        from agent_platform.core.payloads.data_connection import ColumnInfo

        # Get column type
        column_type = str(table[column_name].type())
        if sample_table is not None:
            sample_values = sample_table[column_name].to_pylist()
            # Remove None values
            sample_values = [v for v in sample_values if v is not None]
        else:
            sample_values = None

        return ColumnInfo(
            name=column_name,
            data_type=column_type,
            sample_values=sample_values,
            primary_key=None,  # TODO: Add primary key extraction if available
            unique=None,  # TODO: Add unique if available
            description=None,  # TODO: Add description extraction if available
            synonyms=None,  # TODO: Add synonyms if available
        )
