version: "3"

services:
  postgres:
    image: pgvector/pgvector:pg16
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
      - ./pg_init.sql:/docker-entrypoint-initdb.d/init_db.sql
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
  backend:
    container_name: opengpts-backend
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: "postgres"
      OTEL_COLLECTOR_URL: "http://otel-collector:4318"
    command:
      - --reload
    depends_on:
      - postgres
      - otel-collector
