name: Prep for Release - Bump, Lock, Build Changes
description: |
  This action prepares a branch for release by bumping the version of the named package,
  locking dependencies to match the new versions, and optionally building and pushing changes.
  The package must be defined by its name and have a versionbump.yaml file in its root directory.
  The action will output the new version of the package.

  If the push-changes input is true (the default), the action will push the
  changes to the remote repository. If the push-changes input is true, the
  action will also output the new commit SHA.

  Note: This action expects versionbump to be already set up in the job. Use the
  setup_versionbump action before calling this action.

inputs:
  version-bump-type:
    description: 'The type of version bump to perform'
    required: true
  project-name:
    description: 'The name of the project/package to bump and build changes for'
    required: true
  build-changes:
    description: 'Whether to build the changes'
    required: false
    default: 'true'
  changelog-type:
    description: 'The type of changelog to build, either "prerelease" or "release", defaults to "prerelease"'
    required: false
    default: 'prerelease'
  push-changes:
    description: 'Whether to push the changes'
    required: false
    default: 'true'

outputs:
  new-version:
    description: 'The new version of the package'
    value: ${{ steps.new-version.outputs.new-version }}
  new-commit-sha:
    description: 'The new commit SHA'
    value: ${{ steps.new-commit-sha.outputs.sha }}
  project-path:
    description: 'The path to the project directory'
    value: ${{ steps.get-project-path.outputs.project-path }}

runs:
  using: 'composite'
  steps:
    - name: Get project path
      id: get-project-path
      uses: ./.github/actions/get_project_path
      with:
        project-name: ${{ inputs.project-name }}

    - name: Bump version
      shell: bash
      working-directory: ${{ steps.get-project-path.outputs.project-path }}
      run: versionbump ${{ inputs.version-bump-type }} --no-prompt

    - name: Get new version
      id: new-version
      uses: ./.github/actions/get_version
      with:
        project-name: ${{ inputs.project-name }}

    - name: Relock dependencies
      shell: bash
      run: uv lock

    - name: Commit updated lockfile
      shell: bash
      run: |
        git add uv.lock
        git commit --amend --no-edit

    - name: Generate changelog
      shell: bash
      if: ${{ inputs.build-changes }} == 'true'
      run: |
        uv run python scripts/changes.py build-changes \
          --project ${{ inputs.project-name }} \
          --commit \
          --ci \
          ${{ inputs.changelog-type == 'release' && '--release' || '' }}

    - name: Push changes
      shell: bash
      if: ${{ inputs.push-changes }} == 'true'
      run: git push origin HEAD

    - name: Get new commit SHA
      id: new-commit-sha
      shell: bash
      if: ${{ inputs.push-changes }} == 'true'
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
