from dataclasses import dataclass, field, fields
from typing import Literal

from agent_platform.core.platforms.base import PlatformParameters
from agent_platform.core.utils import SecretString


@dataclass(frozen=True, kw_only=True)
class AzureOpenAIPlatformParameters(PlatformParameters):
    """Parameters for the Azure OpenAI platform.

    This class encapsulates all configuration parameters for Azure OpenAI client
    initialization.
    """

    kind: Literal["azure"] = field(
        default="azure",
        metadata={"description": "The kind of platform parameters."},
        init=False,
    )
    """The kind of platform parameters."""

    azure_api_key: SecretString | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI API key. If not provided, it will be "
            "attempted to be inferred from the environment.",
        },
    )
    """The Azure OpenAI API key. If not provided, it will be attempted to be inferred
    from the environment."""

    azure_endpoint_url: str | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI endpoint URL. If not provided, "
            "it will beattempted to be inferred from the environment.",
        },
    )

    azure_deployment_name: str | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI deployment name. If not provided, "
            "it will be attempted to be inferred from the environment.",
        },
    )

    azure_api_version: str | None = field(
        default="2023-03-15-preview",
        metadata={
            "description": "The Azure OpenAI API version. If not provided, "
            "it will be attempted to be inferred from the environment.",
        },
    )

    azure_deployment_name_embeddings: str | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI deployment name for embeddings. If not "
            "provided, it will be attempted to be inferred from the environment.",
        },
    )

    azure_generated_endpoint_url: str = field(
        default="",
        metadata={
            "description": "The Azure OpenAI generated endpoint URL "
            "(generated by the combination of the endpoint URL "
            "and the deployment name).",
        },
    )

    azure_generated_endpoint_url_embeddings: str = field(
        default="",
        metadata={
            "description": "The Azure OpenAI generated endpoint URL for embeddings "
            "(generated by the combination of the endpoint URL "
            "and the deployment name).",
        },
    )

    azure_model_backing_deployment_name: str | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI model backing deployment name.",
        },
    )

    azure_model_backing_deployment_name_embeddings: str | None = field(
        default=None,
        metadata={
            "description": "The Azure OpenAI model backing deployment name for embeddings.",
        },
    )

    def __post_init__(self):
        from os import getenv

        super().__post_init__()

        if isinstance(self.azure_model_backing_deployment_name_embeddings, list):
            # This value is (currently) unused, and may have been stored (incorrectly) as a
            # list; we will overwrite to None in such a case to normalize it back
            # to the correct type of str | None
            object.__setattr__(
                self,
                "azure_model_backing_deployment_name_embeddings",
                None,
            )

        # Handle case where azure_api_key is passed as a string or dict
        if self.azure_api_key and not isinstance(self.azure_api_key, SecretString):
            object.__setattr__(
                self,
                "azure_api_key",
                SecretString.from_value(self.azure_api_key),
            )
        # Handle case where azure_api_key is not provided
        elif not self.azure_api_key:
            azure_api_key = getenv("azure_api_key")
            if azure_api_key:
                object.__setattr__(
                    self,
                    "azure_api_key",
                    SecretString(azure_api_key),
                )
            else:
                raise ValueError("azure_api_key environment variable is required")

        if self.azure_endpoint_url and self.azure_deployment_name:
            object.__setattr__(
                self,
                "azure_generated_endpoint_url",
                f"{self.azure_endpoint_url}/openai/deployments/{self.azure_deployment_name}/chat/completions?api-version={self.azure_api_version}",
            )
        if self.azure_endpoint_url and self.azure_deployment_name_embeddings:
            object.__setattr__(
                self,
                "azure_generated_endpoint_url_embeddings",
                f"{self.azure_endpoint_url}/openai/deployments/{self.azure_deployment_name_embeddings}/embeddings?api-version={self.azure_api_version}",
            )

    def model_dump(
        self,
        *,
        exclude_none: bool = True,
    ) -> dict:
        """Convert parameters to a dictionary for client initialization.

        Args:
            exclude_none: Whether to exclude fields with value ``None``.
                Defaults to True.
        """
        api_key_value = None
        if self.azure_api_key:
            if isinstance(self.azure_api_key, SecretString):
                api_key_value = self.azure_api_key.get_secret_value()
            else:
                api_key_value = str(self.azure_api_key)

        extra = {
            "azure_api_key": api_key_value,
            "azure_endpoint_url": self.azure_endpoint_url,
            "azure_deployment_name": self.azure_deployment_name,
            "azure_deployment_name_embeddings": self.azure_deployment_name_embeddings,
            "azure_api_version": self.azure_api_version,
            "azure_generated_endpoint_url": self.azure_generated_endpoint_url,
            "azure_generated_endpoint_url_embeddings": self.azure_generated_endpoint_url_embeddings,
            "azure_model_backing_deployment_name": self.azure_model_backing_deployment_name,
            "azure_model_backing_deployment_name_embeddings": (self.azure_model_backing_deployment_name_embeddings),
        }

        return super().model_dump(exclude_none=exclude_none, extra=extra)

    def model_copy(
        self,
        *,
        update: dict | None = None,
    ) -> "AzureOpenAIPlatformParameters":
        """Create a new instance of the model with the same values as
        the current instance.

        Args:
            update: A dictionary of values to update in the new instance.

        Returns:
            A new instance of OpenAIParameters with updated values.
        """
        # Start with current direct parameters
        current_params = {f.name: getattr(self, f.name) for f in fields(self) if f.init}

        if not update:
            current_params = {k: v for k, v in current_params.items() if v is not None}
            return AzureOpenAIPlatformParameters(**current_params)

        # Merge all parameters
        final_params = {**current_params, **update}
        final_params = {k: v for k, v in final_params.items() if v is not None}
        return AzureOpenAIPlatformParameters(**final_params)

    @classmethod
    def model_validate(cls, obj: dict) -> "AzureOpenAIPlatformParameters":
        """Validate and convert a dictionary
        to an AzureOpenAIPlatformParameters instance.

        Args:
            obj: A dictionary of parameters.

        Returns:
            An OpenAIParameters instance.
        """
        obj = dict(obj)  # Create a copy to avoid modifying the original

        # Convert datetime strings back to datetime objects
        cls._convert_datetime_fields(obj)

        # Directly pass the dictionary to the constructor.
        # The constructor and __post_init__ will handle extra parameters.
        return cls(**obj)


PlatformParameters.register_platform_parameters("azure", AzureOpenAIPlatformParameters)
