FROM node:23-alpine

WORKDIR /app

RUN apk upgrade --no-cache && \
  apk add --no-cache npm

COPY package*.json ./

RUN --mount=type=secret,id=npmrc,dst=/app/.npmrc npm install

COPY index.html entrypoint.sh postcss.config.js tailwind.config.js tsconfig.json tsconfig.node.json tsr.config.json vite.config.ts ./

RUN ln -s /app/dist /var/www

EXPOSE 8001

ENTRYPOINT ["npm", "run", "dev"]
