- Expected agent-package/agents/mcp-servers/url to be mutually exclusive with 'command-line'
  field.
- Expected agent-package/agents/mcp-servers/command-line to be mutually exclusive
  with 'url' field.
- Expected transport field to be 'stdio' when using 'command-line' field (found 'streamable-http').
- Expected agent-package/agents/mcp-servers/url to be mutually exclusive with 'command-line'
  field.
- Expected transport field to be one of ['streamable-http', 'sse'] when using 'url'
  field (found 'stdio').
- Expected agent-package/agents/mcp-servers/command-line to be mutually exclusive
  with 'url' field.
