name: Build agent-server Docker image for ACE

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      agent_server_version:
        description: 'Agent Server binary version to use for the Docker image'
        type: string
        required: true
      release_channel:
        description: 'Release channel to publish Docker image on [ci, manual]'
        type: string
        required: true
      agent_server_commit:
        description: 'The commit the binary was built from (informational)'
        type: string
        required: true
      agent_server_branch:
        description: 'The branch the binary was built from (informational)'
        type: string
        required: true

env:
  ECR_ACCOUNT: '024848458368'
  ECR_REGION: 'us-east-1'

defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: '${{ env.ECR_REGION }}'
          role-to-assume: 'arn:aws:iam::${{ env.ECR_ACCOUNT }}:role/github-action-for-ace-repositories-ci'
          role-session-name: GitHub

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Agent Server Image
        env:
          AGENT_SERVER_VERSION: ${{ inputs.agent_server_version }}
          AGENT_SERVER_COMMIT: ${{ inputs.agent_server_commit }}
          AGENT_SERVER_BRANCH: ${{ inputs.agent_server_branch }}
          AGENT_SERVER_RELEASE_CHANNEL: ${{ inputs.release_channel }}
          OCI_REPO_BASE: ${{ env.ECR_ACCOUNT }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com
        run: |
          # Log in to Amazon ECR
          aws ecr get-login-password --region "${ECR_REGION}" | \
            docker login \
              --username "AWS" \
              --password-stdin \
              "${OCI_REPO_BASE}"

          commit_sha="$(git rev-parse --short HEAD)"
          timestamp="$(date +%s)"
          agent_server_image_tag="${AGENT_SERVER_VERSION}-${timestamp}"

          # URL encode the tag for retrieving the binary from CDN
          agent_server_version_encoded="$(echo "${AGENT_SERVER_VERSION}" | jq -Rr @uri)"

          # Build the agent server Docker image
          agent_server_image_repo="${OCI_REPO_BASE}/${AGENT_SERVER_RELEASE_CHANNEL}/ace/agent-server"
          docker buildx build \
            --platform=linux/amd64 \
            --file Dockerfile.ace \
            --tag "${agent_server_image_repo}:${agent_server_image_tag}" \
            --build-arg "AGENT_SERVER_VERSION=${agent_server_version_encoded}" \
            --push \
            .

          # Pass the repo and tag to the next step
          echo "agent_server_image_tag=${agent_server_image_tag}" >> "${GITHUB_ENV}"

          echo "- Docker image ${agent_server_image_repo}:${agent_server_image_tag}" >> "${GITHUB_STEP_SUMMARY}"
          echo "- Agent Server Version: ${AGENT_SERVER_VERSION}" >> "${GITHUB_STEP_SUMMARY}"
          echo "- Agent Server Commit: ${AGENT_SERVER_COMMIT}" >> "${GITHUB_STEP_SUMMARY}"
          echo "- Agent Server Branch: ${AGENT_SERVER_BRANCH}" >> "${GITHUB_STEP_SUMMARY}"
          echo "- Release channel: ${AGENT_SERVER_RELEASE_CHANNEL}" >> "${GITHUB_STEP_SUMMARY}"

      - name: Trigger ACE Publish Workflow
        env:
          ACE_DEPLOY_WORKFLOW_TRIGGER_TOKEN: '${{ secrets.ACE_DEPLOY_WORKFLOW_TRIGGER_TOKEN }}'
        run: |
          echo "Triggering ACE publish workflow"

          if [[ "${{ inputs.release_channel }}" = "ci" ]]; then
            # Build CI ACE version
            ace_prerelease="none"
            invoked_by="agent-server@${{ inputs.agent_server_version }}"
          else
            # Build "manual" (dev, prerelease) ACE version
            repo_name="$(
              echo "${{ github.event.repository.name }}" |
                tr '[:upper:]' '[:lower:]' |
                tr -cd 'a-z-'
            )"
            branch_name="$(
              echo "${{ inputs.agent_server_branch }}" |
                tr '[:upper:]' '[:lower:]' |
                tr -cd 'a-z' |
                cut -c -20
            )"

            # Construct prerelease suffix for ACE release
            ace_prerelease="${repo_name}-agentserver-${branch_name}"

            invoked_by="${{ github.event.repository.name }}/${{ inputs.agent_server_branch }}"
          fi

          ace_ref="master"

          ACTION_PAYLOAD=$(jq -n \
            --arg ref "${ace_ref}" \
            --arg agentServerImageTag "${agent_server_image_tag}" \
            --arg prerelease "${ace_prerelease}" \
            --arg invokedBy "${invoked_by}" \
            '{
              "ref": $ref,
              "inputs": {
                "branch": $ref,
                "agent-server-image-tag": $agentServerImageTag,
                "prerelease": $prerelease,
                "invoked-by": $invokedBy,
              }
            }')

          curl \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${ACE_DEPLOY_WORKFLOW_TRIGGER_TOKEN}" \
            --url "https://api.github.com/repos/Sema4AI/ace/actions/workflows/ace-publish-v2.yml/dispatches" \
            --data "${ACTION_PAYLOAD}" \
            --fail \
            --show-error
