name: Test Agent Server

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    uses: ./.github/workflows/sub-test-unit.yml

  lint:
    uses: ./.github/workflows/sub-test-lint.yml

  typecheck:
    uses: ./.github/workflows/sub-test-typecheck.yml

  format:
    uses: ./.github/workflows/sub-test-format.yml