name: Sai SDK Release

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

  push:
    tags:
      - 'sema4ai-sai-sdk-*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Sai SDK Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typescript-sai-sdk
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      - name: Creating .npmrc
        run: |
          cat << EOF > "./.npmrc"
            registry=https://registry.npmjs.org/
            @robocorp:registry=https://npm.pkg.github.com/
            @sema4ai:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          EOF
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Sai SDK
        run: npm run build

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
