name: Cleanup Dev Deployment

on:
  pull_request:
    types: [unlabeled, closed]

concurrency:
  group: spar-teardown-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  id-token: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-24.04

    if: |
      (github.event.action == 'unlabeled' && github.event.label.name == 'dev_deploy_aws') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'dev_deploy_aws'))

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::017820691865:role/github-deployer-team-edition-1

      - name: Comment on PR
        uses: actions/github-script@v8
        env:
          operation: ${{ github.event.action == 'unlabeled' && 'The `dev_deploy_aws` label was removed' || 'The PR was closed' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.operation }} - tearing down ECS deployment.'
            })

      - name: Run teardown CodeBuild
        uses: aws-actions/aws-codebuild-run-build@4d15a47425739ac2296ba5e7eee3bdd4bfbdd767 # v1
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          OPERATION: teardown
        with:
          project-name: team-edition-dev-deployer-team-edition-1
          env-vars-for-codebuild: BRANCH_NAME,OPERATION
          source-version-override: ${{ github.base_ref }}
