name: Spar UI Changesets check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'workroom/spar-ui/**'

defaults:
  run:
    working-directory: ./workroom/spar-ui/

jobs:
  spar-ui-changesets-check:
    if: github.event.pull_request.title != 'Spar UI:${{ ' ' }}Next Release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: workroom/package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sema4ai'

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Isolate spar-ui package
        run: rm ../package.json

      - name: Check for changesets file
        run: npx changeset status --since=origin/main
