name: Check to ensure a Change Fragment was created

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout (defaults to github.sha)"
        required: false
        type: string
        default: ${{ github.sha }}
      linux-runner:
        description: "The linux runner to use"
        required: false
        type: string
        default: "ubuntu-24.04"

jobs:
  check-changes:
    runs-on: ${{ inputs.linux-runner }}


    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          fetch-tags: true
  
      - uses: ./.github/actions/prep_environment
  
      - name: Run check-changes
        run: make check-changes
        env:
          CI: true
      