name: Workroom Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/workroom-test.yml'
      - 'workroom/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workroom-test.yml'
      - 'workroom/**'

permissions:
  contents: read

jobs:
  test-specs:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./workroom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './workroom/package-lock.json'

      - name: Create .npmrc file
        shell: bash
        run: |
          cat << EOF > .npmrc
          registry=https://registry.npmjs.org/
          @sema4ai:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${{ secrets.SEMA4_CI_USER_PACKAGE_READ_TOKEN }}
          EOF

      - name: Install dependencies
        shell: bash
        run: |
          npm ci

      - name: Build frontend
        shell: bash
        run: |
          npm run build:frontend

      - name: Run tests
        shell: bash
        run: |
          npm run test:specs && npm run test:types

  test-format:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./workroom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './workroom/package-lock.json'

      - name: Create .npmrc file
        shell: bash
        run: |
          cat << EOF > .npmrc
          registry=https://registry.npmjs.org/
          @sema4ai:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=${{ secrets.SEMA4_CI_USER_PACKAGE_READ_TOKEN }}
          EOF

      - name: Install dependencies
        shell: bash
        run: |
          npm ci

      - name: Run linting
        shell: bash
        run: |
          npm run lint
